project_id = "xpfvjkzmoydapxzofphc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"

[db]
port = 54322

[edge_functions]
enabled = true
port = 54323

[storage]
enabled = true
port = 54325

[functions.webhook-hotmart]
verify_jwt = false

[functions.auth-login]
verify_jwt = false

[functions.definir-senha]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.notificar-admin-erro]
verify_jwt = false

[functions.recuperar-senha]
verify_jwt = false

[functions.enviar-resumo-diario]
verify_jwt = false

[functions.health-check-hotmart]
verify_jwt = false

[functions.reenviar-email-manual]
verify_jwt = false