// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpfvjkzmoydapxzofphc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwZnZqa3ptb3lkYXB4em9mcGhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODQ1NjksImV4cCI6MjA2NTA2MDU2OX0.hUeom0yoVwhS_qA9N0DXNDf4x2JLdgpMuVBqHbeO5kQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);